### ISSUE TITLE
Colors by Ticket priority,

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#124]
In Zendesk we do not have a color guidance of what priority is set in a ticket.
It would be nice to have it in order to be able to track them faster. 

Another Chrome extension i found, allowed selecting wich ticket priorities you wanted to highlight, so maybe someone wants to go full "Pride" mode, or maybe highlight the Urgent priority. 

![colors](https://user-images.githubusercontent.com/11269504/53820822-da1f1a00-3f6c-11e9-8901-6d4d2319fd8d.jpg)

**Comment by joelthorner** [comment]
Added into v2.3.2
