### ISSUE TITLE
Custom Macros / Combos

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#133]
Zendesk ofrece la opcion de usar combinaciones de teclado (en adelante combo) para hacer diferentes funciones. ej:
- ctrl+alt+o = Enviar ticket como "open"
- ctrl+alt+u = Actualizar ticket

Por otro lado, hay dos tareas muy habituales en la herramienta que no tienen combo: 
- Asignar ticket a un grupo / usuario
- Modificar el tipo de ticket

Seria la hostia que al pulsar un combo y que te desplegara cada una de estas opciones: 
(Siguiendo el patrón de combos de Zendesk, y teniendo en cuenta de que las acciones de actualizar ticket, enviar como nuevo y enviar como pendiente se hacen con las teclas U, O, P, respectivamente)

ctrl+alt+9 = Abrir (o focus) en el campo "Asignee"
ctrl+alt+8 = Abrir (o focus) en el campo "Type"

Si se pudieran abrir estos campos, casi mejor, porque luego solo seria necesario seleccionar un item de su interior usando las teclas de dirección.

Desconozco si esta funcionalidad es viable.

**Comment by Unoriginal02** [comment]
![download](https://user-images.githubusercontent.com/11269504/55670448-9f1e4800-5884-11e9-854d-46cbeec9e4e3.png)

**Comment by Unoriginal02** [comment]
CTRL + SHFT + ALT + A = Asignee
CTRL + SHFT + ALT + T = Ticket type
CTRL + SHFT + ALT + P = Priority

**Comment by Unoriginal02** [comment]
CTRL + SHFT + ALT + C = Activar / Desactivar check "Comment with CC Team"
CTRL + SHFT + ALT + D = Activar / Desactivar check "Doubts"

(Estos dos son muy especificos de CC)

**Comment by joelthorner** [comment]
Nomes em deixa afegir-ne 4 i tinc fet els 3 primers. 👎 
@joelthorner : En comptes de definir la comanda al manifest, fer-ho per js amb un content_script amb listeners, i fer les combinacions originals. 🏭 

- [x] Command: Ctrl+Shift+F - Focus to assignee field (Zendesk ticket view)
- [x] Command: Ctrl+Shift+K - Focus to type field (Zendesk ticket view)
- [x] Command: Ctrl+Shift+Y - Focus to priority field (Zendesk ticket view)
- [ ] Command: Ctrl+Shift+U - Toggle 'Comment with CC Team' check (Zendesk ticket view)
- [ ] Command: Ctrl+Shift+X - Toggle 'Doubts' check (Zendesk ticket view)

**Comment by Unoriginal02** [comment]
Doncs si només es poden 4, el de prioritats es podria deixar de banda, perque per accedir-hi nomñes faria falta "pitxar" el combo de Type + tab, no?

**Comment by joelthorner** [comment]
Done, a publicar en la proxima release.

- [x] Command: Ctrl+Shift+Alt+A - Focus to assignee field (Zendesk ticket view)
- [x] Command: Ctrl+Shift+Alt+T - Focus to type field (Zendesk ticket view)
- [x] Command: Ctrl+Shift+Alt+P - Focus to priority field (Zendesk ticket view)
- [x] Command: Ctrl+Shift+Alt+C - Toggle 'Comment with CC Team' check (Zendesk ticket view)
- [x] Command: Ctrl+Shift+Alt+D - Toggle 'Doubts' check (Zendesk ticket view)

🥇

**Comment by joelthorner** [comment]
Final Zendesk commands
---------------------

- Ctrl+Shift+Alt+A - Focus to assignee field (Zendesk ticket view)
- Ctrl+Shift+Alt+T - Focus to type field (Zendesk ticket view)
- Ctrl+Shift+Alt+P - Focus to priority field (Zendesk ticket view)
- Ctrl+Shift+Alt+C - Toggle 'Comment with CC Team' check (Zendesk ticket view)
- Ctrl+Shift+Alt+D - Toggle 'Doubts' check (Zendesk ticket view)
- Ctrl+Alt+9 - Prev tab (generic)
- Ctrl+Alt+0 - Next tab (generic)
