### ISSUE TITLE
Broken Zendesk combo

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#134]
Zendesk tiene una combo para moverte entre pestañas: 
ctrl+alt+tab = Next tab
ctrl+alt+shift+tab = Previous tab

El problema es que Windows usa esta misma combinación, por lo que no funciona dentro de Zendesk. 

¿Se podría hacer lo mismo con otra combinación?
ej:
"ctrl+alt+-"
"ctrl+alt+shit+-"

Thanks in advance.

**Comment by joelthorner** [comment]
Ctrl+alt+shit+- La fa sevir Chrome perl zoom i no la podre sobreescriure. Necessito que sigui un altre shortcut.

**Comment by Unoriginal02** [comment]
Bonus track: la combinacio podien ser les següents?:

ctrl+alt+9 = Tab Left
ctrl+alt+0 = Tab Right

El minus (-), no el puc colocar en el tecladillu 👎

**Comment by joelthorner** [comment]
ctrl+alt+9 = Tab Left
ctrl+alt+0 = Tab Right

Confirmed viabilitat

**Comment by joelthorner** [comment]
Done a la proxima release.
