### ISSUE TITLE
Unfocus Comment box

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#137]
Una última request y ya!
Esta es especifica para el teclado: 
Cuando entras en un ticket, el campo del comentario está en focus, como listo para escribir. 
A mi por lo general es una idea que no acaba de convencerme, porque se podría introducir texto involuntario. También entiendo que haya gente a quien le pueda gustar este comportamiento.

Por otro lado, por lo que respecta al tecladillo. Este comportamiento impide que una vez entro en el ticket pueda usar las teclas direccionales para "scrollear", obligándome a coger el ratón. y ya sabes.. eso es tan de 2018...

Si se pudiera hacer algo en forma de checkbox para decidir si quieres o no el focus en el comment box, seria genial.

![download](https://user-images.githubusercontent.com/11269504/55857610-d8e59c00-5b6d-11e9-8c85-eb6855ce82a2.jpg)

Gracias!

**Comment by joelthorner** [comment]
S'intentará implenetar i en tot cas com a opcio de zendesk a options de la extension. Per defecte no activa,

Salut!

**Comment by joelthorner** [comment]
Sembla estable i pujara a la proxima versió.
