### ISSUE TITLE
Duplicado de Submit expander

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#140]
No puedo reproducir este bug con el raton, solo con los comandos de teclado. 
- Abrir un ticket
- ir a las vistas: ctrl+alt+v
- Abrir otro ticket: 
![Untitled2](https://user-images.githubusercontent.com/11269504/56078282-a2ff1c80-5de6-11e9-8b4a-424f7534d50e.gif)

**Comment by joelthorner** [comment]
Que guapu no vec el problema mes boto = millor. xD

Merci pel testing, ho miro!

**Comment by joelthorner** [comment]
He fet el mateix
- Obrir un ticket 
- Ctrl+Alt+v
- Obrir un altre

tot en teclat i no em passa cap cop.

**Comment by Unoriginal02** [comment]
Pot ser mac related?
A mi m'ha passat 10/10

**Comment by Unoriginal02** [comment]
Ok, actualització, Ho he provat en Windows i segueix passant, pero m'he fixat que pot estar una estona sense passar i de cop passar-li a un munt de tickets. 

Ho to do it: 
- Desde la llista de tickets obrirne un fent servir la flecha dreta del teclat.
-Tornar a la vista: ctrl+alt+v
- Obrirne un altre
- Repetir fins que peti.

Salut!

**Comment by joelthorner** [comment]
Ho he repeit durant 15minuts ho he deixat duran altres 15 i despres ho he seguit provant i no em passa.

De fet a nivell de codi es impossible en principi ja que un cop inicialitzat es crea en aquell menu una variable per saber si ha estat inicialitzat o no.

Adicionalment hi ha uns timeouts que impedeixen l'abus de inicialització epr evitar aixo que passa.

Només s'em acut que el teclat custom executi algun comando 2 cops al premer alguna tecla o alguna combinació que faci saltar masses coses de cop, pero tampoc hauria d'afectar al meu script en principi. Ho deixo on-hold i a veure si a la feina passa.

**Comment by Unoriginal02** [comment]
Ara m'hi he passat una bona estona y no aconsegueixo repetir l'error. 
¿?

**Comment by joelthorner** [comment]
No he fet res :/

**Comment by Unoriginal02** [comment]
En el dia a dia no he pogut reproduir l'error de nou. podem tancar la issue, oi?

**Comment by joelthorner** [comment]
Tanco.
