### ISSUE TITLE
Scroll dentro de un ticket con las teclas direccionales

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#143]
Un reciente añadido ha sido el unfocus comment.
Con ello pensaba que ya podría scrollear dentro de los tickets con las teclas direccionales. (hasta ahora hacia el unfocus clicando fura de la caja de texto y dentro de la columna central, donde está el ticket).

Resulta que ahora en cuanto entras en el ticket, te hace el unfocus, pero el scroll sigue sin responder.

¿Seria posible encontrarle una solucion a esto? 
Muchas gracias.

**Comment by joelthorner** [comment]
Ostres podria no ser possible ja que al tenir varis elements en scroll a la web per defecte els navegadors no reconeixen un lloc on fer scroll via arrows i no sembla viable. 

Li donare un parell mes de voltes però.

**Comment by joelthorner** [comment]
No es possible pel funcionament dels navegadors no ho puc controlar.
