### ISSUE TITLE
Focus Comment box xD

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#144]
![353fb1706a0cbc98760eee451089f59a](https://user-images.githubusercontent.com/11269504/56083933-f0ea4380-5e2b-11e9-842a-6e1d8bdf3ead.jpg)

Cuando estoy dentro un ticket y me dispongo a escribir, puedo o bien hacer click en el comment box, (si tengo activado el unfocus de la extension), o bien usar comandos de teclado: 
- ctrl+alt+c: Comentario publico
- ctrl+alt+x: Comentario interno

Mi pregunta es saber si al pulsar uno de esos dos comandos, se podría poner el focus de nuevo en el comment box.

**Comment by joelthorner** [comment]
No es possible amb el disable autofocus.
