### ISSUE TITLE
Custom Macros going funny

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#145]
En principio los shortcuts funcionan **súper bien**.

Pero si pulsas el shortcut de Focus Asignee: Ctrl+Shift+Alt+A, y luego el de Focus Type Field: Ctrl+Shift+Alt+T, se despliega el primero y se activa el focus en el segundo.
Luego si pulsas hacia abajo puedes seleccionar items en ambos.

Dicho asi suena mas a feature que a bug.

Por lo contrario, si pulsas primero Type Field y Luego Asignee, el foco cambia de uno a otro con normalidad.

Salud!

**Comment by Unoriginal02** [comment]
Veo que la macro del Type Field, se "focusea" si le das una ve, y se "unfocusea" si le das de nuevo.

**Comment by joelthorner** [comment]
Aixo es culpa de la estructura i events de camp Assignee que es una merda. Intentaré mirar-ho pero amb una esperança de 50% de solució.

**Comment by joelthorner** [comment]
Update in next release
