### ISSUE TITLE
Unfocus comment box

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#147]
Parece que el unfocus se toma muy a pecho su labor.
![pb](https://user-images.githubusercontent.com/11269504/56118960-5bee6400-5f6b-11e9-8ebd-93eeb5efa145.gif)

Por otro lado, desactivando a opción de "Disable editor autofocus": 
- Sigue "unfocuseando" el editor de texto al entrar en un post.
- Al cambiar entre pestañas (manualmente sin shortcut*), mantiene el foco en el editor de texto,

Los shortcuts siguen haciendo su trabajo unfocuseando al hacer el tab

**Comment by joelthorner** [comment]
💃

**Comment by Unoriginal02** [comment]
🤯

**Comment by joelthorner** [comment]
Fixed
