### ISSUE TITLE
No se abre el popup de "Side conversation"

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#148]
Hola, No se en que momento se ha roto esto, pero al pulsar "side conversation", no aparece el Pop-up con el mensaje. 
![Side Convo](https://user-images.githubusercontent.com/11269504/56122481-c6ef6900-5f72-11e9-809d-a7938775ae12.jpg)
Lo he comprobado con un ZD sin la extensión, para descartar que no fuera un problema de ZD.
Y funcionaba correctamente, 

Muchas gracias de antebrazo.

**Comment by joelthorner** [comment]
🏅

**Comment by joelthorner** [comment]
Update bug fix in next release
