### ISSUE TITLE
Feature request: Avis sobre consum de tickets

### ISSUE THREAD

**Issue by Unoriginal02** [joelthorner/TLmanaGer#163]
Hola, estaria molt xulo poder comprovar quants tickets de suport ha consumit un client en lo que porta de mes.

Actualment aquesta tasca es MOLT MANUAL, i ha un risc molt alt de poder cagarla i no notificar sobre el consum actual de tickets.

Adjunto una imatge de proposta
![download](https://user-images.githubusercontent.com/11269504/62638897-b2c6e180-b93e-11e9-8f91-9dd24b19e030.png)

Al costat del side conversation hi veuras una pastilleta amb el tipus de SLA del client (cada client té un tag amb el tipus de SLA que li pertoca) i amb els tickets de suport que han consumit durant el mes vigent.

D'aquesta manera a l'obrir el tiquet puc veure de forma inequívoca quants tickets ha consumit, i sabré que l'haig de notificar.

Si necessites mes detalls, ho comentem. /hug

**Comment by joelthorner** [comment]
Ja quan tinguis un moment em pots dir els sla/n tiquets?

| SLA    | Tiquets |
|--------|---------|
| Gold   | 6       |
| Silver | 5       |
| ? | ?       |

**Comment by joelthorner** [comment]
Cullons l'he tencat sense voler, tinc progressos hehehe a veure si vana  bon port

**Comment by joelthorner** [comment]
Nota pel jairo, no tinc una vinculacio amb el tiquet la vinculacio ha de ser per customer, quin valor es el del costumert, per exemple de le foto es MASET qui conta tiquets o el usuari Marc pareta ?

**Comment by Unoriginal02** [comment]
Hola, 
Responent a les teves preguntes: 

Els tiquets es comptabilitzen a nivell d'empresa (organization). Per tant en aquest cas, MASET pot obrir 6 tickets de "Petición de soporte" aquest més.

**Et passo una relació de el nº de tickets que li pertoca a cada SLA:**
SLA | Tiquets
-- | --   
Silver | 4
Gold | 6
Platinum | 10

**Et passo una relació dels colors d'avis:** 
Fondo Gris: (un gris suau qualsevol) (amb el text negre o gris fosc)
Fondo Verd: #1da462 (amb el text blanc)
Fondo Groc: #ffcd46 (Amb el text negre o gris fosc)
Fondo Vermell: #dd5144 (Amb el text blanc)

**Relacio de colors i SLA**
**SLA SILVER:**
- de 1 a 2 tk: Gris
- 3 tk: Verd
- 4 tk: Groc
- 5 tk: Vermell

**SLA GOLD:**
- de 1 a 4 tk: Gris
- 5 tk: Verd
- 6 tk: Groc
- 7 tk: Vermell

**SLA PLATINUM:**
- de 1 a 8 tk: Gris
- 9 tk: Verd
- 10 tk: Groc
- 11 tk: Vermell

Desitjos adicionals (valorar viabilitat): 

Ara per ara, les notificacions de consum de tickets no s'aplica a tots els clients, sino a uns pocs escollits. 
Els clients als que s'ha de comptabilitzar els tickets porten una etiqueta: **limittickets**
![download](https://user-images.githubusercontent.com/11269504/62680674-0de8ea80-b9b8-11e9-8892-7152b9a98fba.png)
No se si tens manera de localitzar aquesta etiqueta i utilitzarla per decidir si mostrar o no la notificaciño de consum.

Per últim, i aixo potser es més complicat. Durant el primer mes de proba de les notificacions de consum, vaig veure que hi habia alguns casos en que s'habien de fer excepcions amb alguns clients. 

Per exemple Meisie habia consumit 4 tickets de consultes, pero tenia -1 ticket que li vem perdonar pel motiu que sigui. 

Aquesta excepcionalitat la tenia que apuntar en alguna banda per estar al corrent de la quantitat real de tiquets que habia consumit aquell més.

No se si seria possible en una segona o tercera fase d'aquesta millora afegir la posibilitat de tenir un petit form on posar "-1, -2, ... etc" i que es descomptessin del recompte mensual d'aquell client.
(al principi de més es reiniciaria aquest form)

Moltes gracies!

**Comment by joelthorner** [comment]
Tot fet queda pendent:
- [ ] Restar tiquets by custom filed
- [ ] Limitar-ho a tiquets amb tag concret, o no...

**Comment by joelthorner** [comment]
La gestio de modificacio del consum es guardara al camp notes del organization amb un format semblan sempre en append consrevant les notes actuals:

-----TICKET_RECOUNT_NOT_MODIFY-----
{"data":"key"}
-----END_TICKET_RECOUNT_NOT_MODIFY-----

**Comment by joelthorner** [comment]
POWER_ _ _ _ _ _ value testing:
333222bbbaaLorem ip79sutms a asasdasd

TICKET_RECOUNT_NOT_MODIFY_UNDER_THIS
[{"user":"Jairo","mod":-1,"date":"09/09/2019","reas":"Lorem ipsum dolor sit amet estractum golum mi tesoro"},{"user":"Jairo","mod":-1,"date":"09/09/2019","reas":"Lorem ipsum dolor sit amet estractum golum mi tesoro"},{"date":"2019-08-02","mod":-1,"reas":"3333","user":"333"},{"date":"2019-08-02","mod":-1,"reas":"3333","user":"333"},{"date":"2019-08-14","mod":1,"reas":"123123","user":"343"},{"date":"2019-08-12","mod":1,"reas":"123123","user":"324"},{"date":"2019-08-12","mod":1,"reas":"123123","user":"324"},{"date":"2019-08-13","mod":1,"reas":"123123","user":"111"},{"date":"2019-08-13","mod":1,"reas":"123123","user":"111"},{"date":"2019-08-12","mod":1,"reas":"123123","user":"jjj"}]

**Comment by joelthorner** [comment]
Esta fet pero no publicat, es deixa per dilluns la publicació a la chrome store.

**Comment by joelthorner** [comment]
<ul>
					<li>Only agents</li>
					<li>Auto refresh every 5'</li>
					<li>Option enable/disable this feature</li>
					<li>Depends by: sla, limittickets tag, tickets this month ("intranet") data</li>
					<li>Custom add/delete ticket total</li>
					<li>Clean custom data once time per month</li>
				</ul>

**Comment by Unoriginal02** [comment]
oh mama

Missatge de Joelthorner <notifications@github.com> del dia dv., 16 d’ag.
2019 a les 22:58:

**Comment by joelthorner** [comment]
No ha funcionat per l'https pero he trobat la formula creant/eliminant tabs de forma fancy.

Cal pulirt el codi i ducumanta.

🥇

**Comment by joelthorner** [comment]
Si "funciona" ho donem per "bo" i si surtís alguna cosa, issue nova.

**Comment by joelthorner** [comment]
- [ ] Gumdeu, url a ficar: http://192.168.110.109:12853/zdreports/rtm.cfm
- [ ] ![image](https://user-images.githubusercontent.com/16495000/63997845-fbb62400-caff-11e9-8322-0ccf669178a4.png)

**Comment by joelthorner** [comment]
Change url 
http://192.168.110.109:12853/zdreports/rtm.cfm/?TicketConsume=true
to
http://192.168.110.109:12853/zdreports/rtm.cfm?TicketConsume=true

**Comment by joelthorner** [comment]
Macagundeu ya s'ha de ficar un if al background per evitar obrir tabs quan la opt esta inactiva.

**Comment by joelthorner** [comment]
Tanco el tiquet si surgeix algo issue nova.
